apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-02-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-02-rs
  template:
    metadata:
      name: demo-02-rs
      labels:
        app: demo-02-rs
    spec:
      containers:
        - name: aspnetcore-sample
          image: nishantnepal/aspnetapp:Ingress
          #imagePullPolicy: Always  
          env:
            - name: "VersionPathBase"
              value: "REPLICASETS"
          ports:
          - containerPort: 80
