apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-03-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-03-deploy
  template:
    metadata:
      labels:
        app: demo-03-deploy
    spec:
      containers:
      - name: aspnetcore-sample-dep
        image: nishantnepal/aspnetapp:Ingress
        #imagePullPolicy: Always  
        env:
          - name: "VersionPathBase"
            value: "DEPLOY V1"
        ports:
        - containerPort: 80
