apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-04-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-04-service
  template:
    metadata:
      labels:
        app: demo-04-service
    spec:
      containers:
      - name: aspnetcore-sample-dep
        image: nishantnepal/aspnetapp:Ingress
        #imagePullPolicy: Always  
        env:
          - name: "VersionPathBase"
            value: "SERVICES"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service  
metadata:
  name: demo-04-svc
spec:
  type: NodePort
  selector:
    app: demo-04-service
  ports:
  - port: 8080
    targetPort: 80        
